# -*- coding: utf-8 -*-
"""FeatureScaling_Shyamashree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15P0T4eqHRK7UAk-cEiHDMiD1-a0VywSC
"""

import io
from google.colab import files

uploaded = files.upload()

import numpy as np
import pandas as pd

df = pd.read_csv("Salary_dataset.csv")

df

df = df.drop(['Unnamed: 0'], axis =1)

x = df.iloc[:,:-1]
y = df.iloc[:,-1]

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
ScaledData = sc.fit_transform(x)

scaled_x = pd.DataFrame(ScaledData, columns=x.columns)

scaled_x



