# -*- coding: utf-8 -*-
"""HandlingDuplicate_Shyamashree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/153mf6C5n8PobPhOQ5apPosGySN5JSkBq

**Importing Libraries**
"""

import pandas as pd
import numpy as np
import seaborn as sns

"""**Uploading the dataset**"""

import io
from google.colab import files

uploaded = files.upload()

df = pd.read_csv(io.BytesIO(uploaded.get('Salary Data.csv')))

"""**Handling duplicate value**"""

df

df.head()

df.duplicated().sum()

df.drop_duplicates(inplace=True)

df.duplicated().sum()



