# -*- coding: utf-8 -*-
"""MissingValue_Shyamashree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EKw6C9B57cgYhM42dvnycIk6QCHEGHXc

**Importing Libraries**
"""

import pandas as pd
import numpy as np
import missingno as msno
import seaborn as sns

"""**Loading the Dataset**"""

import io
from google.colab import files

uploaded = files.upload()

df = pd.read_csv("202201-divvy-tripdata.csv")

df

pd.pandas.set_option('Display.max_columns',None)
pd.pandas.set_option('Display.max_rows',None)

"""**Basic Information of the Dataset**"""

df.head()

df.tail()

df.shape

df.info()

df.describe()

df.dtypes

# Visualizing the missing values
msno.bar(df)

sns.heatmap(df.isnull())

df.isnull().sum()

df.dropna(inplace=True)

df['rideable_type'].unique()

df['rideable_type'].value_counts()

len(df['rideable_type'].unique())

df.duplicated().sum()



