# -*- coding: utf-8 -*-
"""OneHotEncoding_Shyamashree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WNPVTr6tf9iKbH38zH0kGYMQGU7lT6mE
"""

from sklearn.preprocessing import OneHotEncoder
import numpy as np
import pandas as pd

data = ['Red','Green','Blue']
encoder = OneHotEncoder(sparse=False, handle_unknown='ignore')
colors_2d = np.array(data).reshape(-1,1)
one_hot_encoded = encoder.fit_transform(colors_2d)
print(one_hot_encoded)

data = {'category':['A','B','C','A','D','B']}
df = pd.DataFrame(data)
encoder = OneHotEncoder(sparse=False)
encoded_data = encoder.fit_transform(df[['category']])

df_encoded = pd.DataFrame(encoded_data, columns=encoder.get_feature_names_out(['category']))

df_encoded









