# -*- coding: utf-8 -*-
"""Polynomial_and_KNN_Shyamashree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KGC58LOemVsCUaMjlEsRDKKnAsg5v33i

**Polynomial Regression**
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

import io
from google.colab import files

uploaded = files.upload()

df = pd.read_csv("Salary_dataset.csv")

df.drop(['Unnamed: 0'], axis=1,inplace=True)

df

x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

# Fitting Polynomial Regression to the dataset
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

poly = PolynomialFeatures(degree=4)
x_poly = poly.fit_transform(x)

poly.fit(x_poly, y)
lin2 = LinearRegression()
lin2.fit(x_poly, y)

# Visualising the Polynomial Regression results
plt.scatter(x, y, color='blue')

plt.plot(x, lin2.predict(poly.fit_transform(x)),
         color='red')
plt.title('Polynomial Regression')
plt.xlabel('YearsExperience')
plt.ylabel('Salary')

plt.show()







"""**KNN**"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

import io
from google.colab import files

uploaded = files.upload()

df = pd.read_csv("loan_data_set.csv")

df

#Checking for missing values
df.isnull().sum()

#Filling Gender column by mode
df['Gender']=df['Gender'].fillna(df['Gender'].mode().values[0])
#Filling Married column by mode
df['Married']=df['Married'].fillna(df['Married'].mode().values[0])
#Filling Dependents column by mode
df['Dependents']=df['Dependents'].fillna(df['Dependents'].mode().values[0])
#Filling Self_Employed column by mode
df['Self_Employed']=df['Self_Employed'].fillna(df['Self_Employed'].mode().values[0])
#Filling LoanAmount column by mean
df['LoanAmount']=df['LoanAmount'].fillna(df['LoanAmount'].mean())
#Filling Loan_Amount_Term column by mode
df['Loan_Amount_Term']=df['Loan_Amount_Term'].fillna(df['Loan_Amount_Term'].mode().values[0] )
#Filling Credit_History column by mode
df['Credit_History']=df['Credit_History'].fillna(df['Credit_History'].mode().values[0] )

#Checking missing values after imputation
df.isna().sum()

#Dropping unnecessary columns
df.drop('Loan_ID', axis=1, inplace=True)

#Converting some object data type to int
gender = {"Female": 0, "Male": 1}
yes_no = {'No' : 0,'Yes' : 1}
dependents = {'0':0,'1':1,'2':2,'3+':3}
education = {'Not Graduate' : 0, 'Graduate' : 1}
property = {'Semiurban' : 0, 'Urban' : 1,'Rural' : 2}
output = {"N": 0, "Y": 1}
df['Gender'] = df['Gender'].replace(gender)
df['Married'] = df['Married'].replace(yes_no)
df['Dependents'] = df['Dependents'].replace(dependents)
df['Education'] = df['Education'].replace(education)
df['Self_Employed'] = df['Self_Employed'].replace(yes_no)
df['Property_Area'] = df['Property_Area'].replace(property)
df['Loan_Status'] = df['Loan_Status'].replace(output)

df.head()

#Setting the value for dependent and independent variables
x = df.drop('Loan_Status', 1)
y = df.Loan_Status

#Splitting the dataset
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test= train_test_split(x, y, test_size= 0.25, random_state=38, stratify = y)

#Fitting the KNN model
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 5)
knn.fit(X_train, Y_train)

#Fitting the KNN model
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 5)
knn.fit(X_train, Y_train)

#Prediction of test set
prediction_knn = knn.predict(X_test)
#Print the predicted values
print("Prediction for test set: {}".format(prediction_knn))

#Actual value and the predicted value
a = pd.DataFrame({'Actual value': Y_test, 'Predicted value': prediction_knn})
a.head()

#Confusion matrix and classification report
from sklearn import metrics
import seaborn as sns
from sklearn.metrics import classification_report, confusion_matrix
matrix = confusion_matrix(Y_test, prediction_knn)
sns.heatmap(matrix, annot=True, fmt="d")
plt.title('Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('True')
print(classification_report(Y_test, prediction_knn))









